import { v4 as uuidv4 } from "uuid";
const activity = {
  configs: {
    grid_props: {
      maxH: 72,
      maxW: 8,
      minH: 10,
      minW: 3,
    },
    props: {
      title: "Activity",
      styles: {},
      refresh: false,
      data_source: [],
      field_update: true,
      hidden: false,
      disable: false,
      show_widget_title: false,
      allow_navigation: true,
      widget_border_disabled: false,
    },
    dynamically_binded: [],
    icon: {
      type: "material-icons-outlined",
      name: "10k",
      color: "#5f6368",
      svg: "memo",
      style: "solid",
      version: 1,
    },
    color: "#FFA500",
    type: "activity",
    display_name: "activity",
    description: "activity description",
    is_refresh: false,
  },
  is_default: true,
  is_active: true,
  widget_version: 1.0,
};
const attachment = {
  configs: {
    display_name: "attachments",
    icon: {
      type: "material-icons-outlined",
      name: "10k",
      color: "#5f6368",
      svg: "memo",
      style: "solid",
      version: 1,
    },
    color: "#FFA500",
    type: "attachment",
    description: "attachment description",
    is_refresh: false,
    dynamically_binded: [],
    grid_props: {
      maxH: 72,
      maxW: 8,
      minH: 10,
      minW: 3,
    },
    props: {
      icon: true,
      title: "Attachments",
      refresh: false,
      author: true,
      sort_by: "newest",
      styles: {},
      file_size: true,
      file_extension: true,
      bulk_action: true,
      hidden: false,
      disable: false,
      show_widget_title: false,
      allow_navigation: true,
      widget_border_disabled: false,
    },
  },
  is_default: true,
  is_active: true,
  widget_version: 1.0,
};
const button = {
  configs: {
    display_name: "button",
    icon: {
      type: "material-icons-outlined",
      name: "10k",
      color: "#5f6368",
      svg: "memo",
      style: "solid",
      version: 1,
    },
    color: "#FFA500",
    type: "button",
    description: "button description",
    is_refresh: false,
    dynamically_binded: [],
    grid_props: {
      maxH: 10,
      maxW: 10,
      minH: 2,
      minW: 1,
    },
    props: {
      color: "",
      refresh: false,
      label: "Button",
      title: "Button",
      hidden: false,
      show_widget_title: false,
      on_success: [],
      run_script: [],
      run_custom_script: [],
      go_to_url: "",
      modal_config: "",
      disable: false,
      bgcolor: "#2E72FF",
      variant: "contained",
      eventhandler: "",
      open_in_new_tab: false,
      confirmation_modal: false,
      confirmation_title: "Are you sure you want to run the script?",
      message: "",
      cancel_text: "No",
      accept_text: "Yes",
      is_sync: false,
      allow_navigation: true,
      border_radius: 8,
      show_icon: false,
      widget_border_disabled: false,
      open_page: false,
      connections: false,
    },
  },
  is_default: true,
  is_active: true,
  widget_version: 1.0,
};
const calendar = {
  configs: {
    display_name: "calendar",
    icon: {
      type: "material-icons-outlined",
      name: "10k",
      color: "#5f6368",
      svg: "memo",
      style: "solid",
      version: 1,
    },
    color: "#FFA500",
    type: "calendar",
    description: "Calendar decs",
    dynamically_binded: [],
    grid_props: {
      maxH: 72,
      maxW: 72,
      minH: 25,
      minW: 12,
    },
    props: {
      title: "Calendar",
      hidden: false,
      disable: false,
      show_widget_title: false,
      views: ["month", "week", "work_week", "day", "agenda"],
      data_source: {},
      defaultView: "AGENDA",
      startAccessor: "start",
      endAccessor: "end",
      filter: [],
      allow_navigation: true,
      visibleAttribute: ["name", "status", "priority"],
      groupBy: "",
      widget_border_disabled: false,
      show_attribute_label: true,
      page: {},
      record_render: "side",
    },
  },
  is_default: true,
  is_active: true,
  widget_version: 1.0,
};
const carousel = {
  configs: {
    display_name: "Carousel",
    icon: {
      type: "material-icons-outlined",
      name: "10k",
      color: "#5f6368",
      svg: "memo",
      style: "solid",
      version: 1,
    },
    color: "#FFA500",
    type: "carousel",
    description: "carousel decs",
    dynamically_binded: [],
    grid_props: {
      maxH: 72,
      maxW: 72,
      minH: 18,
      minW: 4,
    },
    props: {
      title: "Carousel",
      hidden: false,
      disable: false,
      show_widget_title: false,
      allow_navigation: true,
      images: [],
      auto_play: true,
      interval: 2000,
      objectFit: "fill",
      widget_border_disabled: false,
    },
  },
  is_default: true,
  is_active: true,
  widget_version: 1.0,
};
const chart = {
  configs: {
    display_name: "Chart",
    icon: {
      type: "material-icons-outlined",
      name: "10k",
      color: "#5f6368",
      svg: "memo",
      style: "solid",
      version: 1,
    },
    color: "#FFA500",
    type: "chart",
    description: "Chart",
    is_refresh: false,
    dynamically_binded: [],
    grid_props: {
      maxH: 72,
      maxW: 12,
      minH: 1,
      minW: 1,
    },
    props: {
      hidden: false,
      disable: false,
      show_widget_title: true,
      title: "Chart",
      allow_navigation: true,
      chart_name: "bar",
      data_source: {},
      slice_by: "",
      metric: "",
      innerRadius: 0.5,
      metric_on_attribute: "",
      reverse: false,
      layout: "vertical",
      legend_position: {
        anchor: "bottom-right",
        translateX: 120,
        translateY: 0,
      },
      enable_total: true,
      breakdown: "",
      totalsOffset: 10,
      main_axis: {
        legend: "",
        tickSize: 5,
        tickPadding: 5,
        tickRotation: 0,
        legendPosition: "middle",
        legendOffset: -50,
      },
      data_axis: {
        legend: "",
        tickSize: 5,
        tickPadding: 5,
        tickRotation: 0,
        legendPosition: "middle",
        legendOffset: -50,
      },
      labelSkipWidth: 12,
      labelSkipHeight: 12,
      group_mode: "stacked",
      enable_area: false,
      enable_grid_x: true,
      enable_grid_y: true,
      color: { type: "schema", schema_name: "nivo" },
      margin: {
        top: 50,
        right: 160,
        bottom: 50,
        left: 60,
      },
      line_width: 1,
      point_size: 5,
      stages: [],
      order_by: [{ dayOfWeek: "asc" }],
      filter: {
        operator: "AND",
        value: [],
      },
      widget_border_disabled: false,
      group_by: "date",
      custom_filter: [],
      enable_arc_labels: true,
      enable_arc_link_labels: true,
      show_legends: false,
      redirection_url: "",
      filter_key_mapping: {},
    },
  },
  is_default: true,
  is_active: true,
  widget_version: 1.0,
};
const comment = {
  configs: {
    display_name: "comments",
    icon: {
      type: "material-icons-outlined",
      name: "10k",
      color: "#5f6368",
      svg: "memo",
      style: "solid",
      version: 1,
    },
    color: "#FFA500",
    type: "comment",
    description: "comment description",
    dynamically_binded: [],
    grid_props: {
      maxH: 72,
      maxW: 8,
      minH: 15,
      minW: 3,
    },
    props: {
      title: "Comments",
      refresh: false,
      sort_by: "newest",
      styles: {},
      show_sort: true,
      date_format: "relative",
      show_filter: true,
      show_search: true,
      hidden: false,
      disable: false,
      show_widget_title: false,
      allow_navigation: true,
      widget_border_disabled: false,
    },

    is_refresh: false,
  },
  is_default: true,
  is_active: true,
  widget_version: 1.0,
};
const container = {
  configs: {
    display_name: "Container",
    icon: {
      type: "material-icons-outlined",
      name: "10k",
      color: "#5f6368",
      svg: "memo",
      style: "solid",
      version: 1,
    },
    color: "#FFA500",
    type: "container",
    description: "container decs",
    dynamically_binded: [],
    grid_props: {
      maxH: 72,
      maxW: 12,
      minH: 1,
      minW: 1,
    },
    name: "container",
    props: {
      layout: 3,
      children: [],
      title: "Container",
      refresh: false,
      hidden: false,
      disable: false,
      show_widget_title: false,
      widget_border_disabled: false,
      allow_navigation: true,
      sync_with_tab: false,
      tab_widget_id: "",
      default_active_index: 0,
      hide_padding: false,
      bg_color: "#fff",
      gap: 10,
      enable_scroll_button: false,
      enable_force_scroll: false,
    },
  },
  is_default: true,
  is_active: true,
  widget_version: 1.0,
};
const conversation = {
  configs: {
    grid_props: {
      maxH: 72,
      maxW: 12,
      minH: 10,
      minW: 3,
    },
    props: {
      title: "Conversation",
      styles: {},
      refresh: false,
      background_color: "#fff",
      data_source: [],
      hidden: false,
      disable: false,
      show_widget_title: false,
      allow_navigation: true,
      widget_border_disabled: false,
      outgoing_actions: [],
    },
    dynamically_binded: [],
    icon: {
      type: "material-icons-outlined",
      name: "10k",
      color: "#5f6368",
      svg: "memo",
      style: "solid",
      version: 1,
    },
    color: "#FFA500",
    type: "conversation",
    display_name: "Conversation",
    description: "Conversation description",
    is_refresh: false,
  },
  is_default: true,
  is_active: true,
  widget_version: 1.0,
};
const dropdown = {
  configs: {
    display_name: "dropdown",
    icon: {
      type: "material-icons-outlined",
      name: "10k",
      color: "#5f6368",
      svg: "memo",
      style: "solid",
      version: 1,
    },
    color: "#FFA500",
    type: "dropdown",
    description: "dropdown decs",
    dynamically_binded: [],
    is_refresh: false,
    grid_props: {
      maxH: 72,
      maxW: 72,
      minH: 4,
      minW: 2,
    },
    props: {
      mode: "mapped",
      title: "Dropdown",
      refresh: false,
      columns: "",
      data_source: "",
      placeholder: "",
      manual_options: [],
      hidden: false,
      disable: false,
      show_widget_title: false,
      allow_navigation: true,
      widget_border_disabled: false,
    },
  },
  is_default: true,
  is_active: true,
  widget_version: 1.0,
};
const file_preview = {
  configs: {
    display_name: "File Preview",
    icon: {
      type: "material-icons-outlined",
      name: "10k",
      color: "#5f6368",
      svg: "memo",
      style: "solid",
      version: 1,
    },
    color: "#FFA500",
    type: "file_preview",
    description: "file preview description",
    dynamically_binded: [],
    grid_props: {
      maxH: 72,
      maxW: 8,
      minH: 10,
      minW: 2,
    },
    props: {
      title: "File Preview",
      refresh: false,
      styles: {},
      variant: "static",
      file_type: "auto",
      data_source: "",
      run_script: [],
      show_download: true,
      show_delete: true,
      show_edit: true,
      source_url: "",
      hidden: false,
      disable: false,
      on_success: [],
      show_widget_title: false,
      allow_camera_access: true,
      multiple_file_support: false,
      allow_navigation: true,
      widget_border_disabled: false,
    },
    is_refresh: false,
  },
  is_default: true,
  is_active: true,
  widget_version: 1.0,
};
const header = {
  configs: {
    display_name: "header",
    icon: {
      type: "material-icons-outlined",
      name: "10k",
      color: "#5f6368",
      svg: "memo",
      style: "solid",
      version: 1,
    },
    color: "#FFA500",
    type: "header",
    description: "header desc",
    dynamically_binded: [],
    grid_props: {
      maxH: 72,
      maxW: 12,
      minH: 2,
      minW: 3,
    },
    props: {
      icon: {
        name: "",
        type: "",
        color: "",
      },
      title: "Header",
      widget_title: "Header",
      refresh: false,
      styles: {},
      actions: [],
      alignment: "1",
      action_spacing: "auto",
      action_count: "4",
      attribute_spacing: "auto",
      icon_type: "dynamic",
      show_icon: true,
      attributes: [],
      data_source: [],
      show_title: true,
      title_type: "dynamic",
      show_actions: true,
      show_breadcrumb: true,
      show_action_icon: false,
      row_attribute_count: "5",
      override_style: false,
      title_size: "large",
      widget_background_color: "",
      widget_border_radius: "",
      widget_outline: "",
      widget_shadow: "",
      hidden: false,
      disable: false,
      show_widget_title: false,
      allow_navigation: true,
      label_attribute: "name",
      widget_border_disabled: false,
    },
    is_refresh: false,
  },
  is_default: true,
  is_active: true,
  widget_version: 1.0,
};
const html_parser = {
  configs: {
    display_name: "HTML Parser",
    icon: {
      type: "material-icons-outlined",
      name: "10k",
      color: "#5f6368",
      svg: "memo",
      style: "solid",
      version: 1,
    },
    color: "#FFA500",
    type: "html_parser",
    description: "HTML Parser Description",
    dynamically_binded: [],
    grid_props: {
      maxH: 72,
      maxW: 12,
      minH: 2,
      minW: 2,
    },
    props: {
      title: "HTML Parser",
      styles: {},
      hidden: false,
      disable: false,
      show_widget_title: false,
      htmlContent: "",
      widget_border_disabled: false,
    },
    is_refresh: false,
    buttonsConfig: [],
    iframeConfig: [],
  },
  is_default: true,
  is_active: true,
  widget_version: 1.0,
};
const iframe = {
  configs: {
    display_name: "iframe",
    icon: {
      type: "material-icons-outlined",
      name: "10k",
      color: "#5f6368",
      svg: "memo",
      style: "solid",
      version: 1,
    },
    color: "#FFA500",
    type: "iframe",
    description: "Iframe Description",
    dynamically_binded: [],
    grid_props: {
      maxH: 72,
      maxW: 12,
      minH: 4,
      minW: 2,
    },
    props: {
      url: "https://www.amoga.io/",
      type: "static",
      title: "Iframe",
      isSuperset: false,
      styles: {},
      hidden: false,
      disable: false,
      show_widget_title: false,
      allow_navigation: true,
      widget_border_disabled: false,
    },
    is_refresh: false,
  },
  is_default: true,
  is_active: true,
  widget_version: 1.0,
};
const json = {
  configs: {
    display_name: "JSON",
    icon: {
      type: "material-icons-outlined",
      name: "10k",
      color: "#5f6368",
      svg: "memo",
      style: "solid",
      version: 1,
    },
    color: "#FFA500",
    type: "json",
    description: "JSON Widget",
    dynamically_binded: [],
    grid_props: {
      maxH: 72,
      maxW: 12,
      minH: 27,
      minW: 6,
    },
    props: {
      title: "JSON",
      source_attribute: "",
      hidden: false,
      disable: false,
      show_widget_title: false,
      allow_navigation: true,
      widget_border_disabled: false,
    },

    is_refresh: false,
  },
  is_default: true,
  is_active: true,
  widget_version: 1.0,
};
const jsonform = {
  configs: {
    display_name: "Json Form",
    icon: {
      type: "material-icons-outlined",
      name: "10k",
      color: "#5f6368",
      svg: "memo",
      style: "solid",
      version: 1,
    },
    color: "#FFA500",
    type: "jsonform",
    description: "Json forms desc",
    dynamically_binded: [],
    grid_props: {
      maxH: 72,
      maxW: 12,
      minH: 4,
      minW: 3,
    },
    props: {
      hidden: false,
      disable: false,
      show_widget_title: true,
      allow_navigation: true,
      title: "Json Form",
      form_layout: [],
      data_source: {},
      mode: "update",
      related_keys: [],
      is_custom_form: false,
      init_script: `async (params) => {
                console.log("Init script",params)
                return {}
            }`,
      execute_init: false,
      execute_save: false,
      save_script: `async (params) => {
                console.log("Save script",params)
                return {}
            }`,
      save_button: "Save",
      cancel_button: "Cancel",
      action_button_flex: false,
      widget_border_disabled: false,
      background: "#ffffff",
      primary_button: [],
      secondary_button: [],
    },
    is_refresh: false,
  },
  is_default: true,
  is_active: true,
  widget_version: 1.0,
};
const leaderboard = {
  configs: {
    display_name: "leaderboard",
    icon: {
      type: "material-icons-outlined",
      name: "leaderboard",
      color: "#5f6368",
      svg: "memo",
      style: "solid",
      version: 1,
    },
    color: "#FFA500",
    type: "leaderboard",
    description: "leaderboard description",
    is_refresh: false,
    dynamically_binded: [],
    grid_props: {
      maxH: 100,
      maxW: 12,
      minH: 2,
      minW: 1,
    },
    props: {
      color: "",
      label: "leaderboard",
      title: "leaderboard",
      hidden: false,
      show_widget_title: false,
      disable: false,
      bgcolor: "#2E72FF",
      border_radius: 8,
      widget_border_disabled: true,
      query: "",
      transformer:
        "(result, global) => {\n    // transform result and return\n    return result;\n}",
      dynamic_list: false,
      show_my_rank: false,
      no_of_results: 10,
      score_icon: { version: 1, svg: "badge-dollar" },
    },
  },
  is_default: true,
  is_active: true,
  widget_version: 1.0,
};
const list = {
  configs: {
    display_name: "List",
    icon: {
      type: "material-icons-outlined",
      name: "10k",
      color: "#5f6368",
      svg: "memo",
      style: "solid",
      version: 1,
    },
    color: "#FFA500",
    type: "list",
    description: "List description",
    is_refresh: false,
    dynamically_binded: [],
    grid_props: {
      maxH: 72,
      maxW: 12,
      minH: 5,
      minW: 1,
    },
    props: {
      title: "List",
      schema: {},
      hidden: false,
      disable: false,
      show_widget_title: false,
      widget_border_disabled: false,
    },
  },
  is_default: true,
  is_active: true,
  widget_version: 1.0,
};
const map = {
  configs: {
    display_name: "Map",
    icon: {
      type: "material-icons-outlined",
      name: "map",
      color: "#5f6368",
      svg: "map",
      style: "solid",
      version: 1,
    },
    color: "#2bc0b4",
    type: "map",
    description: "Map Description",
    is_refresh: true,
    dynamically_binded: [],
    grid_props: {
      maxH: 72,
      maxW: 12,
      minH: 2,
      minW: 2,
    },
    props: {
      title: "",
      refresh: false,
      hidden: false,
      disable: false,
      show_widget_title: false,
      widget_background_color: "#FFFFFF",
      separator_color: "#E2E8F0",
      locations: [],
      marker_radius: 10000,
      item_spacing: 16,
      direction: "left",
      dynamic_data: false,
      show_optimal_route: false,
      query: "",
      transformer:
        "(result, global) => {\n    // transform result and return\n    return result;\n}",
      page: {},
      record_render: "side",
      map_actions: [],
    },
  },
  is_default: true,
  is_active: true,
  widget_version: 1.0,
};
const page = {
  configs: {
    display_name: "page",
    type: "page",
    icon: {
      type: "material-icons-outlined",
      name: "10k",
      color: "#5f6368",
      svg: "memo",
      style: "solid",
      version: 1,
    },
    color: "#FFA500",
    description: "Page Description",
    dynamically_binded: [],
    grid_props: {
      maxH: 72,
      maxW: 12,
      minH: 10,
      minW: 3,
    },

    props: {
      title: "Page",
      pagelist: "",
      styles: {},
      enable: "{{}}",
      color: "{{}}",
      hidden: false,
      disable: false,
      show_widget_title: false,
      allow_navigation: true,
      widget_border_disabled: false,
    },
  },
  is_default: true,
  is_active: true,
  widget_version: 1.0,
};
const path = {
  configs: {
    display_name: "path",
    icon: {
      type: "material-icons-outlined",
      name: "10k",
      color: "#5f6368",
      svg: "memo",
      style: "solid",
      version: 1,
    },
    color: "#FFA500",
    type: "path",
    description: "Path",
    dynamically_binded: [],
    is_refresh: false,
    grid_props: {
      maxH: 72,
      maxW: 12,
      minH: 4,
      minW: 3,
    },
    props: {
      refresh: false,
      title: "Path",
      sequence: {},
      data_source: "",
      object_slug: "",
      styles: {},
      hidden: false,
      disable: false,
      show_widget_title: false,
      allow_navigation: true,
      widget_border_disabled: false,
    },
  },
  is_default: true,
  is_active: true,
  widget_version: 1.0,
};
const progressbar = {
  configs: {
    display_name: "Progress Bar",
    icon: {
      type: "material-icons-outlined",
      name: "10k",
      color: "#5f6368",
      svg: "memo",
      style: "solid",
      version: 1,
    },
    color: "#FFA500",
    type: "progressbar",
    description: "progressbar decs",
    dynamically_binded: [],
    is_refresh: false,
    grid_props: {
      maxH: 72,
      maxW: 12,
      minH: 1,
      minW: 1,
    },
    props: {
      color: "#233B55",
      refresh: false,
      label: false,
      query: {},
      title: "Progress bar",
      variant: "determinate",
      progresstype: "linear",
      hidden: false,
      disable: false,
      show_widget_title: false,
      allow_navigation: true,
      widget_border_disabled: false,
    },
  },
  is_default: true,
  is_active: true,
  widget_version: 1.0,
};

const qrScanner = {
  configs: {
    display_name: "QR Scanner",
    icon: {
      type: "material-icons-outlined",
      name: "10k",
      color: "#5f6368",
      svg: "memo",
      style: "solid",
      version: 1,
    },
    color: "#FFA500",
    type: "qrscanner",
    description: "QR scanner's description",
    dynamically_binded: [],
    grid_props: {
      maxH: 10,
      maxW: 10,
      minH: 2,
      minW: 1,
    },
    props: {
      title: "QR Scanner",
      label: "Scanner",
      hidden: false,
      disable: false,
      show_widget_title: false,
      go_to_url: "",
      open_in_new_tab: false,
      run_script: [],
      eventhandler: "go_to_url",
      close_after_scan: false,
      confirmation_modal: false,
      ignore_duplicate: false,
      confirmation_title: "Are you sure you want to run scirpt",
      message: "",
      cancel_text: "No",
      accept_text: "Yes",
      allow_navigation: true,
      widget_border_disabled: false,
    },
  },
  is_default: true,
  is_active: true,
  widget_version: 1.0,
};
const richTextEditor = {
  configs: {
    display_name: "Rich Text Editor",
    icon: {
      type: "material-icons-outlined",
      name: "10k",
      color: "#5f6368",
      svg: "memo",
      style: "solid",
      version: 1,
    },
    color: "#FFA500",
    type: "richTextEditor",
    description: "Rich Text Editor description",
    dynamically_binded: [],
    grid_props: {
      maxH: 72,
      maxW: 12,
      minH: 15,
      minW: 7,
    },
    props: {
      title: "Rich Text Editor",
      source_attribute: "",
      hidden: false,
      disable: false,
      show_widget_title: false,
      allow_navigation: true,
      widget_border_disabled: false,
    },

    is_refresh: false,
  },
  is_default: true,
  is_active: true,
  widget_version: 1.0,
};
const spacer = {
  configs: {
    display_name: "spacer",
    icon: {
      type: "material-icons-outlined",
      name: "10k",
      color: "#5f6368",
      svg: "memo",
      style: "solid",
      version: 1,
    },
    color: "#FFA500",
    type: "spacer",
    description: "spacer decs",
    dynamically_binded: [],
    grid_props: {
      maxH: 72,
      maxW: 72,
      minH: 1,
      minW: 1,
    },
    props: {
      title: "Spacer",
      hidden: false,
      disable: false,
      show_widget_title: false,
      allow_navigation: true,
      widget_border_disabled: false,
    },
  },
  is_default: true,
  is_active: true,
  widget_version: 1.0,
};
const stats = {
  configs: {
    display_name: "stats",
    icon: {
      type: "material-icons-outlined",
      name: "10k",
      color: "#5f6368",
      svg: "stats",
      style: "solid",
      version: 1,
    },
    color: "#FFA500",
    type: "stats",
    description: "Stats Description",
    is_refresh: true,
    dynamically_binded: [],
    grid_props: {
      maxH: 14,
      maxW: 6,
      minH: 4,
      minW: 1,
    },
    props: {
      title: "Stats",
      refresh: false,
      hidden: false,
      disable: false,
      show_widget_title: false,
      info: false, // addons
      source_type: "measure",
      source_value: "",
      label: "",
      icon: {
        type: "material-icons-outlined",
        name: "trending_up",
        style: "light",
        svg: "chart-line",
        color: "#5f6368",
        version: 1,
      },
      icon_type: "secondary",
      icon_alignment: "left",
      format: "number",
      secondary_text: "",
      align: "left",
      bg_color: "#ffffff",
      is_action: false,
      action: "set_filter",
      page_link: "",
      open_in: "redirect",
      filter: true,
      query_value: "",
      tooltip: "", // addons
      suffix_text: "", // addons
      prefix_text: "", // addons
      allow_navigation: true,
      show_icon: true,
      border_color: "",
      widget_border_disabled: false,
      currency_format: "",
      add_text: "",
    },
  },
  is_default: true,
  is_active: true,
  widget_version: 1.0,
};
const table = {
  configs: {
    type: "table2",
    display_name: "table2",
    icon: {
      type: "material-icons-outlined",
      name: "10k",
      color: "#5f6368",
      svg: "table",
      style: "solid",
      version: 1,
    },
    color: "#FFA500",
    description: "table description",
    dynamically_binded: [],
    is_refresh: false,
    grid_props: {
      maxH: 72,
      maxW: 12,
      minH: 25,
      minW: 6,
    },
    props: {
      refresh: false,
      page: {},
      sort: [],
      title: "Table",
      filter: [],
      columns: [],
      data_source: {},
      density: true,
      tree_view: true,
      stick_bottom: false,
      sort_allow: true,
      create_allow: true,
      filter_allow: true,
      search_allow: true,
      create_type: { key: "tooljet", value: "", name: "Tooljet" },
      reorder_allow: true,
      // enable_view: false,
      bulk_action_allow: true,
      show_vertical_border: true,
      show_checkbox_on_hover: true,
      show_horizontal_border: true,
      quick_filters: [],
      hidden: false,
      disable: false,
      show_widget_title: false,
      pagination_limit: 15,
      actions: [],
      record_render: "side",
      adhoc_tasks: [],
      export_allow: false,
      enable_show_closed: true,
      show_card_on_mobile: true,
      enable_bulk_delete: true,
      custom_filter: [],
      enable_saved_views: false,
      saved_views: [],
      child_record_page: {},
    },
  },
  is_default: true,
  is_active: true,
  widget_version: 2.0,
};

const tabs = {
  configs: {
    display_name: "tabs",
    icon: {
      type: "material-icons-outlined",
      name: "10k",
      color: "#5f6368",
      svg: "memo",
      style: "solid",
      version: 1,
    },
    color: "#FFA500",
    type: "tab",
    description: "tab decs",
    dynamically_binded: [],
    grid_props: {
      maxH: 72,
      maxW: 12,
      minH: 10,
      minW: 3,
    },
    name: "tabs",
    props: {
      type: {
        name: "Tabs",
        value: "tabs",
      },
      stick_bottom: false,
      current_tab: 0,
      linear: false,
      styles: "",
      children: [
        {
          ...iframe,
          configs: {
            ...iframe.configs,
            tab_id: uuidv4(),
          },
        },
      ],
      default_children: ["iframe"],
      show_back_button: true,
      show_next_button: true,
      peek_mode: { name: "Full", value: "full" },
      color: false,
      enable: true,
      title: "Tabs",
      refresh: false,
      hidden: false,
      disable: false,
      show_widget_title: false,
      allow_navigation: true,
      hide_nav: false,
      view: "standard",
      dynamic_list: false,
      query: "",
      transformer:
        "(result, global) => {\n    // transform result and return\n    return result;\n}",
      show_scroll_button: true,
      widget_border_disabled: false,
    },
  },
  is_default: true,
  is_active: true,
  widget_version: 1.0,
};
const ticker = {
  configs: {
    display_name: "ticker",
    icon: {
      type: "material-icons-outlined",
      name: "10k",
      color: "#5f6368",
      svg: "ticker",
      style: "solid",
      version: 1,
    },
    color: "#FFA500",
    type: "ticker",
    description: "Ticker Description",
    is_refresh: true,
    dynamically_binded: [],
    grid_props: {
      maxH: 6,
      maxW: 12,
      minH: 2,
      minW: 2,
    },
    props: {
      title: "",
      refresh: false,
      hidden: false,
      disable: false,
      show_widget_title: false,
      widget_background_color: "#FFFFFF",
      separator_color: "#E2E8F0",
      ticker_data: [],
      animation_duration: 25,
      item_spacing: 16,
      direction: "left",
      dynamic_data: false,
      query: "",
      transformer:
        "(result, global) => {\n    // transform result and return\n    return result;\n}",
    },
  },
  is_default: true,
  is_active: true,
  widget_version: 1.0,
};
// Export all widgets
export const widgets = {
  activity,
  attachment,
  button,
  calendar,
  carousel,
  chart,
  comment,
  container,
  conversation,
  dropdown,
  file_preview,
  header,
  html_parser,
  iframe,
  json,
  jsonform,
  leaderboard,
  list,
  map,
  page,
  path,
  progressbar,
  qrScanner,
  richTextEditor,
  spacer,
  stats,
  table,
  tabs,
  ticker,
};
